### ISSUE TITLE
How do you mock the parent or top properties?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simonihmig/ember-window-mock#175]
Does this add-on already mock parent and top?

**Comment by simonihmig** [comment]
No, there is nothing specific here regarding those properties. What exactly would expect it to do?

**Comment by NullVoxPopuli** [comment]
Specifically, I'd like to set the window.parent.location.href, but not window.location.href

**Comment by NullVoxPopuli** [comment]
it seems like window.location always === window.parent.location :thinking:
